export enum CONSTANT {
  BLOCKED_BY_VIEWER = '该用户已被拉黑，无法查看',
  BLOCK_YOURSELF = '你无法拉黑自己',
  RESPONSE_CODE_500 = '服务器开小差了',
  EPISODE_STATUS_REMOVED = '此单集已删除',
  LOGIN_TOOLTIP = '使用小宇宙 APP 绑定的手机号登录',
  NO_BIO = '这个人很懒，什么都没留下',
  LOGIN_FAILED = '登录失败，请检查验证码或稍后再尝试登录',
  RECENT_PLAYED_HIDDEN = '不让他人看到我的收听记录',
  LISTEN_MILEAGE_HIDDEN_IN_COMMENT = '不在评论区展示收听时长标签',
  STICKER_LIBRARY_HIDDEN = '不让他人看到我的贴纸库',
  STICKER_BOARD_HIDDEN = '不让他人看到我的贴纸装扮',
  REJECT_HOT_PUSH = '接受热门内容推送',
  REJECT_RECOMMEND_ACTION = '个性化推荐',
  IP_LOC_HIDDEN = '不展示 IP 属地信息',
  GOOGLE_URL = 'https://www.google.com/',
  GITHUB_URL = 'https://www.github.com/',
  NO_PLAY = '未在播放',
  PLAYER_FAST_FORWARD = '向前 15 秒',
  PLAYER_REWIND = '向后 15 秒',
  PLAYER_PLAY = '播放',
  PLAYER_PAUSE = '暂停',
  PLAYER_LIKED = '收藏',
  PLAYER_UNLIKED = '取消收藏',
}
