const DISCOVERY_TYPE_ENUM = {
  POPULAR: 'DISCOVERY_EPISODE_RECOMMEND',
  EDITOR_RECOMMENDED: 'EDITOR_PICK',
  RECOMMENDED: 'DISCOVERY_COLLECTION',
  PEOPLE_LIKE: 'DISCOVERY_PICK',
}

export { DISCOVERY_TYPE_ENUM }
